all:
	gcc -pthread -o borders_pthread borders_pthread.c
	gcc -pthread -o borders_pthread_cache borders_pthread_cache.c
	
	gcc -o borders borders.c
	gcc -o borders_cache borders_cache.c
	
	gcc -o borders_clone borders_clone.c
	gcc -o borders_clone_cache borders_clone_cache.c